### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Josh4Jesus** [Josh4Jesus/memverse-mobile-app#1]
My Html file isn't reding my CSS file. How do I fix this?

**Comment by liuning9** [comment]
Introducing the problem or is covered?

**Comment by Josh4Jesus** [comment]
The problem with css is covered.

**Comment by liuning9** [comment]
If the browser CSS cover off his CSS, that way you can use higher level priority such as ID! Important, if other framework class CSS himself quoted words, can adjust the loading sequence of CSS file or important. Of course, important method is not the best!

**Comment by liuning9** [comment]
I just look at your code, may be to use the 480 resolution, but you do not, all elements with no reference to css. The usage of "media= only screen and (max-width: 480px)" I have not tried, but should not work, CSS2 media query should not provide such usage, why don't you try CSS3 mediaScreen
